import { OrbitControls, useAnimations, useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { Suspense, useEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { engine } from '../audio/ToneEngine'
import { BAND_COUNT, readBands } from '../audio/harmonics'
import modelUrl from '../assets/models/chakra_model.glb?url'

/**
 * An interactive 3D scene for the frequency app.
 *
 * `chakra_model.glb` is generated by `scripts/make-chakra-model.mjs` rather than
 * downloaded — a column of light with seven chakra spheres inside an aura, and
 * one four second `idle` clip that breathes. That matters for reading this file:
 * the node names below (`aura`, `body`) exist because that script puts them
 * there, and a different model would need the lookup adjusted.
 *
 * The frequency drives three things, and they are deliberately different
 * quantities rather than one number wired three ways:
 *
 *   - Hue, if no colour is given. An octave of pitch is a full turn of the
 *     wheel, so 396Hz and 792Hz are the same colour, which is the relationship
 *     the sound actually has.
 *   - Pulse rate, as the frequency folded into a rate a person can watch. A
 *     literal 528Hz pulse is invisible and unpleasant; folding by octaves down
 *     to between a half and one hertz keeps it proportional and calm.
 *   - Glow, which rises with pitch, because higher frequencies read as brighter.
 *
 * Everything is eased toward its target rather than set, so changing frequency is
 * a transition rather than a cut.
 */

const MODEL_URL = modelUrl

/**
 * The chakras sit between y = -1.25 and y = 1.25 in the model, root at the
 * bottom. This maps a node's height onto the interval that answers for it.
 */
const bandOf = (y: number) =>
  Math.max(0, Math.min(BAND_COUNT - 1, Math.round(((y + 1.25) / 2.5) * (BAND_COUNT - 1))))

/**
 * The aura, as a fresnel shell.
 *
 * A physical material was the obvious reach and the wrong one: `transmission`
 * needs its own render pass and does not combine with additive blending, so the
 * aura came out as a flat grey ellipse sitting in front of the figure rather than
 * as light around it. What actually reads as a hologram is much simpler — be
 * transparent where the surface faces you and bright where it turns away, which
 * is the fresnel term, drawn on the inside of the sphere and added rather than
 * blended. The travelling bands are the other half of the look, and they cost one
 * sine.
 */
const AURA_VERTEX = /* glsl */ `
  varying vec3 vNormal;
  varying vec3 vView;
  varying vec3 vLocal;
  void main() {
    vLocal = position;
    vNormal = normalize(normalMatrix * normal);
    vec4 viewPosition = modelViewMatrix * vec4(position, 1.0);
    vView = normalize(-viewPosition.xyz);
    gl_Position = projectionMatrix * viewPosition;
  }
`

const AURA_FRAGMENT = /* glsl */ `
  uniform vec3 uColor;
  uniform float uIntensity;
  uniform float uTime;
  varying vec3 vNormal;
  varying vec3 vView;
  varying vec3 vLocal;
  void main() {
    float facing = abs(dot(normalize(vNormal), normalize(vView)));
    float rim = pow(1.0 - facing, 2.6);
    // Bands running up the shell, so the surface is legible as a surface.
    float bands = 0.78 + 0.22 * sin(vLocal.y * 14.0 - uTime * 1.6);
    float alpha = rim * uIntensity * bands;
    gl_FragColor = vec4(uColor * alpha, alpha);
  }
`

/** Reference pitch for the hue mapping — the app's own centre. */
const REFERENCE_HZ = 432

/**
 * Frequency to hue: one octave, one full turn. Anything at the same pitch class
 * gets the same colour whatever octave it is played in.
 */
export function hueFor(frequencyHz: number): number {
  if (!(frequencyHz > 0)) return 0
  const octaves = Math.log2(frequencyHz / REFERENCE_HZ)
  return ((octaves % 1) + 1) % 1
}

/**
 * Frequency to a rate the eye can follow: halved by octaves until it lands
 * between 0.5 and 1Hz, so the pulse stays proportional to the pitch without ever
 * becoming a flicker.
 */
export function pulseRateFor(frequencyHz: number): number {
  if (!(frequencyHz > 0)) return 0.5
  let rate = frequencyHz
  while (rate > 1) rate /= 2
  while (rate < 0.5) rate *= 2
  return rate
}

type FigureProps = {
  frequencyHz: number
  color?: string
  /**
   * Read the app's own audio and answer to it, rather than only to the frequency
   * number. Off by default so the component stays what the brief asked for — a
   * scene driven by two props — and only becomes part of the app when the app
   * asks it to. Inside the frame loop it costs one FFT read, and the loop is
   * already running.
   */
  reactive?: boolean
}

/**
 * The motes around the figure.
 *
 * Deterministic, not random: a scene that comes back different every mount is
 * harder to look at and impossible to compare screenshots of. They sit in a
 * cylindrical shell around the column and rise, wrapping at the top, so the field
 * reads as a current rather than as a cloud.
 */
const MOTE_COUNT = 900

function useMotes() {
  return useMemo(() => {
    const positions = new Float32Array(MOTE_COUNT * 3)
    const speeds = new Float32Array(MOTE_COUNT)
    let seed = 528
    const next = () => {
      seed = (seed * 1103515245 + 12345) & 0x7fffffff
      return seed / 0x7fffffff
    }
    for (let i = 0; i < MOTE_COUNT; i++) {
      const angle = next() * Math.PI * 2
      const radius = 0.35 + Math.pow(next(), 0.6) * 1.5
      positions[i * 3] = Math.cos(angle) * radius
      positions[i * 3 + 1] = -1.8 + next() * 3.6
      positions[i * 3 + 2] = Math.sin(angle) * radius
      speeds[i] = 0.05 + next() * 0.16
    }
    const geometry = new THREE.BufferGeometry()
    geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3))
    // A point is a square unless it is given a sprite, and 900 squares read as
    // static rather than as motes. One 64px radial gradient fixes it.
    const sprite = document.createElement('canvas')
    sprite.width = sprite.height = 64
    const sctx = sprite.getContext('2d')!
    const halo = sctx.createRadialGradient(32, 32, 0, 32, 32, 32)
    halo.addColorStop(0, 'rgba(255,255,255,1)')
    halo.addColorStop(0.35, 'rgba(255,255,255,0.5)')
    halo.addColorStop(1, 'rgba(255,255,255,0)')
    sctx.fillStyle = halo
    sctx.fillRect(0, 0, 64, 64)
    const texture = new THREE.CanvasTexture(sprite)

    const material = new THREE.PointsMaterial({
      size: 0.05,
      map: texture,
      sizeAttenuation: true,
      transparent: true,
      opacity: 0.85,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
    })
    return { geometry, material, texture, positions, speeds }
  }, [])
}

function Figure({ frequencyHz, color, reactive = false }: FigureProps) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(MODEL_URL)

  /**
   * Cloned, not used directly. `useGLTF` caches by URL and hands every caller the
   * same object graph, so mounting this twice — or mounting it again after an
   * unmount that disposed anything — would have two scenes sharing one set of
   * nodes. The clone is cheap next to the load it avoids repeating.
   */
  const model = useMemo(() => scene.clone(true), [scene])
  const { actions, mixer } = useAnimations(animations, model)

  /** The materials this component owns, and must dispose of. */
  const owned = useMemo(() => {
    const aura = new THREE.ShaderMaterial({
      uniforms: {
        uColor: { value: new THREE.Color(0.4, 0.6, 1) },
        uIntensity: { value: 1 },
        uTime: { value: 0 },
      },
      vertexShader: AURA_VERTEX,
      fragmentShader: AURA_FRAGMENT,
      transparent: true,
      depthWrite: false,
      side: THREE.BackSide,
      blending: THREE.AdditiveBlending,
    })
    const emissive = new Map<THREE.Mesh, THREE.MeshPhysicalMaterial>()
    return { aura, emissive }
  }, [])

  // Swap in the materials this component controls, and remember the originals so
  // the cached scene graph is left as it was found.
  useEffect(() => {
    const replaced: { mesh: THREE.Mesh; material: THREE.Material | THREE.Material[] }[] = []
    model.traverse((child) => {
      if (!(child instanceof THREE.Mesh)) return
      replaced.push({ mesh: child, material: child.material })
      if (child.name === 'aura') {
        child.material = owned.aura
        return
      }
      const source = Array.isArray(child.material) ? child.material[0] : child.material
      const base = source as THREE.MeshStandardMaterial
      const material = new THREE.MeshPhysicalMaterial({
        color: base.color?.clone() ?? new THREE.Color(0xffffff),
        emissive: base.emissive?.clone() ?? new THREE.Color(0x000000),
        emissiveIntensity: 1,
        roughness: 0.3,
        metalness: 0,
        // Opaque on purpose. Transmission and a low opacity turned seven
        // saturated colours into seven pastel ones — with the ambient light kept
        // low, the emissive term is what shows, and it shows the actual colour.
        transparent: false,
      })
      owned.emissive.set(child, material)
      child.material = material
    })
    return () => {
      for (const { mesh, material } of replaced) mesh.material = material
    }
  }, [model, owned])

  // The looping breath. Named rather than "whatever is first", so a model with
  // more than one clip does not start playing an arbitrary one.
  useEffect(() => {
    const idle = actions.idle ?? Object.values(actions)[0]
    idle?.reset().setLoop(THREE.LoopRepeat, Infinity).fadeIn(0.6).play()
    return () => {
      idle?.fadeOut(0.4)
      // Uncaches this clip's bindings; without it the mixer holds the scene graph
      // alive after the component is gone.
      mixer.stopAllAction()
      mixer.uncacheRoot(model)
    }
  }, [actions, mixer, model])

  /** Everything created here is disposed here — geometry belongs to the cache. */
  useEffect(
    () => () => {
      owned.aura.dispose()
      for (const material of owned.emissive.values()) material.dispose()
      owned.emissive.clear()
    },
    [owned],
  )

  const motes = useMotes()
  useEffect(
    () => () => {
      motes.geometry.dispose()
      motes.material.dispose()
      motes.texture.dispose()
    },
    [motes],
  )

  const target = useMemo(() => new THREE.Color(), [])
  const eased = useMemo(() => new THREE.Color(0.4, 0.6, 1), [])

  /**
   * Per-interval levels, when reactive. The same reading the rest of the app's
   * visualisers use, so a fifth sounds like a fifth here too — and the seven
   * intervals land on the seven chakras in order, bottom to top, which is the
   * mapping the model was built around.
   */
  const audio = useMemo(
    () => ({
      bands: new Float32Array(BAND_COUNT),
      rise: new Float32Array(BAND_COUNT),
      level: 0,
      phase: 0,
    }),
    [],
  )

  useFrame((_, delta) => {
    // Guard the tab having been in the background: `delta` can arrive as several
    // seconds, which would snap every eased value instead of easing it.
    const step = Math.min(delta, 1 / 20)

    if (color) target.set(color)
    else target.setHSL(hueFor(frequencyHz), 0.85, 0.55)
    eased.lerp(target, 1 - Math.exp(-step * 2.5))

    audio.phase += step
    if (reactive) {
      readBands(audio.bands, audio.rise, engine.getSpectrum(), frequencyHz, engine.sampleRate, audio.phase)
      let sum = 0
      for (let i = 0; i < BAND_COUNT; i++) sum += audio.bands[i]
      audio.level += (sum / BAND_COUNT - audio.level) * 0.12
    }

    const pulse = 0.5 + 0.5 * Math.sin(performance.now() * 0.001 * pulseRateFor(frequencyHz) * Math.PI * 2)
    // Higher pitches read as brighter, over about four octaves.
    const brightness = THREE.MathUtils.clamp(Math.log2(frequencyHz / 120) / 4, 0, 1)
    // When the sound is driving, it drives: the idle pulse stays underneath as a
    // floor so a silent moment is calm rather than dark.
    const drive = reactive ? Math.max(pulse * 0.35, audio.level * 1.6) : pulse
    // Kept under about 1.2: an emissive term past that clips each channel to
    // full and seven distinct colours converge on white, which is what happened
    // at 0.85 + 0.7 + 0.5.
    const intensity = 0.45 + brightness * 0.3 + drive * 0.28

    owned.aura.uniforms.uColor.value.copy(eased)
    owned.aura.uniforms.uIntensity.value = 0.75 + drive * 0.6 + brightness * 0.45
    owned.aura.uniforms.uTime.value += step

    for (const [mesh, material] of owned.emissive) {
      // The chakras keep their own colours and take the frequency's only as a
      // tint, so the model still reads as itself at every pitch — a third of the
      // way across was the difference between seven colours and seven white
      // blobs.
      material.emissive.lerpColors(material.color, eased, 0.3)
      // Reactive, each chakra answers to its own interval — bottom to top, the
      // order the scale runs in. Otherwise the pulse simply travels up the column,
      // phased by height so the whole thing does not flash at once.
      const lit = reactive
        ? audio.bands[bandOf(mesh.position.y)]
        : 0.5 +
          0.5 *
            Math.sin(
              performance.now() * 0.001 * pulseRateFor(frequencyHz) * Math.PI * 2 -
                mesh.position.y * 0.9,
            )
      material.emissiveIntensity = intensity + lit * 0.55
    }

    // The motes rise and wrap, faster when there is more light in the scene.
    const { positions, speeds } = motes
    const lift = step * (0.4 + brightness * 0.8 + drive * 0.9)
    for (let i = 0; i < MOTE_COUNT; i++) {
      let y = positions[i * 3 + 1] + speeds[i] * lift
      if (y > 1.8) y -= 3.6
      positions[i * 3 + 1] = y
    }
    motes.geometry.attributes.position.needsUpdate = true
    motes.material.color.copy(eased)
    motes.material.opacity = 0.45 + drive * 0.35

    if (group.current) group.current.rotation.y += step * 0.08
  })

  return (
    <group ref={group}>
      <primitive object={model} />
      <points geometry={motes.geometry} material={motes.material} />
      {/* Two lights that follow the frequency, so its colour is in the shading
          and not only in the emission. */}
      <pointLight position={[2.5, 2, 2.5]} intensity={6} distance={12} decay={2} color={eased} />
      <pointLight position={[-2.5, -1.5, -2]} intensity={3.5} distance={12} decay={2} color={eased} />
    </group>
  )
}

export type ChakraSceneProps = FigureProps & {
  /** Replaces the default sizing entirely — pass one and size it yourself. */
  className?: string
  /** Off by default, per the brief; useful for an unattended screen. */
  autoRotate?: boolean
}

export function ChakraScene({
  frequencyHz,
  color,
  className,
  autoRotate = false,
  reactive = false,
}: ChakraSceneProps) {
  return (
    // Sized inline rather than with utility classes: a canvas in a box with no
    // height is a canvas 150 pixels tall, and this component should not depend on
    // the host page having loaded the app's stylesheet to avoid that.
    <div
      className={className}
      style={className ? { background: '#000000' } : { width: '100%', height: '100%', background: '#000000' }}
    >
      <Canvas
        camera={{ position: [0, 0, 6], fov: 42 }}
        dpr={[1, 2]}
        gl={{ antialias: true, alpha: false, powerPreference: 'high-performance' }}
        onCreated={({ gl, scene }) => {
          gl.setClearColor('#000000', 1)
          scene.background = new THREE.Color('#000000')
        }}
      >
        {/* Low, so the emissive colours carry the scene rather than being washed
            out by a flat fill. */}
        <ambientLight intensity={0.16} />
        <Suspense fallback={null}>
          <Figure frequencyHz={frequencyHz} color={color} reactive={reactive} />
        </Suspense>
        <OrbitControls
          enableDamping
          dampingFactor={0.06}
          autoRotate={autoRotate}
          autoRotateSpeed={0.4}
          enablePan={false}
          minDistance={3.5}
          maxDistance={11}
          // Kept off the poles: looking straight down the column is a dot, and
          // looking up from under it is the inside of the aura.
          minPolarAngle={Math.PI * 0.22}
          maxPolarAngle={Math.PI * 0.78}
        />
      </Canvas>
    </div>
  )
}

useGLTF.preload(MODEL_URL)
