import { PORT, BOOT, openApp, wait } from '../harness.mjs'

/**
 * A shared link opens the thing that was shared.
 *
 * The point of sharing here is not the sheet — it is that the person on the
 * other end taps a line in a chat and lands on that exact journey, in an app
 * they have never opened. Which means the interesting half happens in a browser
 * with no history, no settings and no store: the state the sender had cannot be
 * relied on for anything.
 *
 * So the links are generated by the app itself and then opened in a **fresh
 * context**, the way a stranger would open them.
 */
export const name = 'share'
export const about = 'a shared link opens the journey, for someone who has never opened the app'

const JOURNEY = 'journey-innerspace-7'
const FREQUENCY = 'sol-639'

export async function run(browser) {
  const { ctx, page, errors } = await openApp(browser)
  // The links exactly as the share sheet would send them.
  const links = await page.evaluate(
    async ([journeyId, freqId]) => {
      const { shareLink, shareMessage } = await import('/src/lib/share.ts')
      const { getJourney, journeyTitle } = await import('/src/lib/catalog.ts')
      return {
        journey: shareLink({ kind: 'journey', id: journeyId }),
        frequency: shareLink({ kind: 'frequency', id: freqId }),
        message: shareMessage({ kind: 'journey', id: journeyId }, 'he'),
        title: journeyTitle(getJourney(journeyId), 'he'),
      }
    },
    [JOURNEY, FREQUENCY],
  )
  await ctx.close()

  /** Opens a link the way somebody who has never seen the app would. */
  const asStranger = async (url) => {
    const fresh = await browser.newContext({ viewport: { width: 390, height: 844 } })
    // Only the opening notice is pre-dismissed — everything else is a first
    // visit, including having no settings and no journey progress.
    await fresh.addInitScript((s) => localStorage.setItem('settings', JSON.stringify(s)), {
      ...BOOT, headphoneNoticeSeen: true,
    })
    const p = await fresh.newPage()
    p.on('pageerror', (e) => errors.push(`stranger: ${e.message.slice(0, 140)}`))
    await p.goto(url)
    await wait(1600)
    for (let i = 0; i < 10 && (await p.locator('[role=dialog]').count()); i++) {
      await p.locator('[role=dialog]').first().dispatchEvent('click').catch(() => {})
      await wait(400)
    }
    const seen = { text: await p.evaluate(() => document.body.innerText), hash: await p.evaluate(() => location.hash) }
    await fresh.close()
    return seen
  }

  const journeyVisit = await asStranger(links.journey)
  const freqVisit = await asStranger(links.frequency)

  const failures = []
  if (!links.journey.includes(`#/journey/${JOURNEY}`)) failures.push(`journey link is wrong: ${links.journey}`)
  if (!links.journey.startsWith(`http://localhost:${PORT}/`)) failures.push('the link does not point at this app')
  if (!links.message.includes(links.journey)) failures.push('the message does not carry the link')
  if (!links.message.includes(links.title)) failures.push('the message does not name the journey')
  // The ask for reports is the point of sending it to anyone yet, and it has to
  // come after the link rather than before it.
  if (!links.message.includes('ספר לי')) failures.push('the message does not ask for reports')
  if (links.message.indexOf('ספר לי') < links.message.indexOf(links.journey)) {
    failures.push('the message asks for bug reports before it says what it is')
  }

  if (!journeyVisit.text.includes(links.title)) failures.push('a stranger opening the journey link does not see the journey')
  // The invitation is the reason for sharing: it is how the receiver learns
  // this is an app they can keep.
  if (!journeyVisit.text.includes('נשלח אליך')) failures.push('the shared-with-you invitation is missing')
  // Asking for a report without naming a channel is decoration; the log is the
  // channel, and the card has to say so.
  if (!journeyVisit.text.includes('יומן אבחון')) failures.push('the invitation does not say where to report')

  if (!freqVisit.text.includes('639')) failures.push('a stranger opening the frequency link does not get that frequency')
  // The invitation has to survive the address being cleaned up, which happens
  // on a shared frequency the moment it is applied.
  if (!freqVisit.text.includes('נשלח אליך')) failures.push('the invitation is missing on a shared frequency')
  // The address is cleaned up, or every later visit to the player silently
  // re-selects whatever was once shared.
  if (freqVisit.hash.includes(FREQUENCY)) failures.push(`the frequency stayed in the address: ${freqVisit.hash}`)

  return {
    rows: [
      { link: links.journey.replace(`http://localhost:${PORT}/`, '…/'), lands: journeyVisit.text.includes(links.title) ? links.title : 'nothing' },
      { link: links.frequency.replace(`http://localhost:${PORT}/`, '…/'), lands: freqVisit.text.includes('639') ? '639 Hz' : 'nothing' },
    ],
    failures,
    errors,
  }
}
