import { describe, expect, it } from 'vitest'
import figure from './figure.json'

/**
 * The point cloud is generated by `scripts/extract-figure.mjs` and committed, so
 * nothing at runtime would notice if a regeneration went wrong — the renderer
 * would just draw whatever it was handed. These are the properties the drawing
 * depends on, and most of them are here because they have been wrong once.
 */
const data = figure as unknown as {
  width: number
  height: number
  scale: number
  top: number
  bottom: number
  baseHue: number
  count: number
  nodes: number
  p: number[]
}

/** Circular mean of a set of hues in degrees. */
function meanHue(hues: number[]): number {
  let u = 0
  let v = 0
  for (const h of hues) {
    u += Math.cos((h * Math.PI) / 180)
    v += Math.sin((h * Math.PI) / 180)
  }
  return (((Math.atan2(v, u) * 180) / Math.PI) + 360) % 360
}

/** Smallest angle between two hues, in degrees. */
function apart(a: number, b: number): number {
  return Math.abs((((a - b) % 360) + 540) % 360 - 180)
}

const points = () => {
  const out: { x: number; y: number; luma: number; hue: number; node: boolean }[] = []
  for (let i = 0; i < data.p.length; i += 4) {
    out.push({
      x: data.p[i],
      y: data.p[i + 1],
      luma: data.p[i + 2],
      hue: ((data.p[i + 3] >> 1) / 64) * 360,
      node: (data.p[i + 3] & 1) === 1,
    })
  }
  return out
}

describe('figure point cloud', () => {
  it('is a flat quadruple-packed array of the declared length', () => {
    expect(data.p.length).toBe(data.count * 4)
    expect(data.p.every(Number.isInteger)).toBe(true)
  })

  it('is dense enough to read as a body rather than as dust', () => {
    expect(data.count).toBeGreaterThan(25000)
  })

  it('spans the declared extent, and the extent is a standing figure', () => {
    const ys = points().map((p) => p.y)
    expect(Math.min(...ys)).toBe(data.top)
    expect(Math.max(...ys)).toBe(data.bottom)
    const xs = points().map((p) => p.x)
    const height = data.bottom - data.top
    const width = Math.max(...xs) - Math.min(...xs)
    // Taller than wide, or it is not a person standing with their arms down.
    expect(height).toBeGreaterThan(width)
  })

  it('keeps brightness and hue inside the bits they are stored in', () => {
    for (const p of points()) {
      expect(p.luma).toBeGreaterThanOrEqual(0)
      expect(p.luma).toBeLessThanOrEqual(63)
      expect(p.hue).toBeGreaterThanOrEqual(0)
      expect(p.hue).toBeLessThan(360)
    }
  })

  it('carries lit points, but as a minority of the cloud', () => {
    const nodes = points().filter((p) => p.node)
    expect(nodes.length).toBe(data.nodes)
    expect(nodes.length).toBeGreaterThan(100)
    expect(nodes.length).toBeLessThan(data.count / 4)
  })

  it('declares the mean hue the renderer rotates from', () => {
    const measured = meanHue(points().map((p) => p.hue))
    // Within a few degrees: the stored hues are quantised to six bits.
    expect(apart(measured, data.baseHue)).toBeLessThan(5)
  })

  /**
   * The mapping the whole visualiser rests on: the artwork's colour runs from red
   * at the feet through the spectrum to violet at the crown, which is why height
   * can stand for interval. If a future source loses that, the bands would still
   * light up but they would no longer mean anything.
   */
  it('runs a spectrum up the body rather than one colour', () => {
    const all = points()
    const height = data.bottom - data.top
    const low = all.filter((p) => p.y > data.bottom - height * 0.25)
    const high = all.filter((p) => p.y < data.top + height * 0.25)
    expect(apart(meanHue(low.map((p) => p.hue)), meanHue(high.map((p) => p.hue)))).toBeGreaterThan(30)
  })
})
