import { describe, expect, it } from 'vitest'
import figure from './figure.json'

/**
 * The point cloud is generated by `scripts/extract-figure.mjs` and committed, so
 * nothing at runtime would notice if a regeneration went wrong — the renderer
 * would just draw whatever it was handed and the figure would quietly stop being
 * a person. These are the properties the drawing depends on.
 */
const data = figure as unknown as {
  width: number
  scale: number
  shellInner: number
  coreOuter: number
  maxRadius: number
  count: number
  p: number[]
}

describe('figure point cloud', () => {
  it('is a flat quadruple-packed array of the declared length', () => {
    expect(data.p.length).toBe(data.count * 4)
    expect(data.p.every(Number.isInteger)).toBe(true)
  })

  it('nests the three radii the renderer separates on', () => {
    expect(data.shellInner).toBeLessThan(data.coreOuter)
    expect(data.coreOuter).toBeLessThan(data.maxRadius)
  })

  it('carries all three kinds, with the body the largest group', () => {
    const counts = [0, 0, 0]
    for (let i = 3; i < data.p.length; i += 4) counts[data.p[i]]++
    expect(counts[0]).toBeGreaterThan(0)
    expect(counts[1]).toBeGreaterThan(0)
    expect(counts[2]).toBeGreaterThan(0)
    // If the interior ever outnumbers the body again, the chest is back to
    // hiding the person, which is the defect this labelling exists to fix.
    expect(counts[0]).toBeGreaterThan(counts[2])
  })

  it('places every point in the group its radius says it is in', () => {
    // Coordinates are stored as integers, so a radius measured back out of them
    // can sit up to a unit either side of the boundary it was classified on.
    const slack = 1.5
    for (let i = 0; i < data.p.length; i += 4) {
      const r = Math.hypot(data.p[i], data.p[i + 1])
      const kind = data.p[i + 3]
      if (kind === 2) expect(r).toBeLessThan(data.shellInner + slack)
      else if (kind === 1) expect(r).toBeGreaterThan(data.shellInner - slack)
      else expect(r).toBeGreaterThan(data.coreOuter - slack)
      expect(r).toBeLessThan(data.maxRadius + slack)
    }
  })

  it('keeps brightness in the six bits it is stored in', () => {
    for (let i = 2; i < data.p.length; i += 4) {
      expect(data.p[i]).toBeGreaterThanOrEqual(0)
      expect(data.p[i]).toBeLessThanOrEqual(63)
    }
  })

  it('is dense enough to read as a drawing rather than as dust', () => {
    expect(data.count).toBeGreaterThan(25000)
  })
})
